[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.5.0-dev.9"
hdk = "=0.4.0-dev.10"
serde = "1"
holochain = "0.4.0-dev.12"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
